spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: 123456
    driver: org.postgresql.Driver

app:
  security:
    header: "user-token"
    token: "secretadmin123"